### ISSUE TITLE
Return different geohash level

### ISSUE THREAD

**Issue by dhthong92** [derrickpelletier/geohash-poly#13]
Dear sir, could I return different geohash level (precision) in one run? Beside it, could you tell me more details about your algorithm? How can you find the row bounding? Does it look like the image below? Another problem that I still don't understand is that how you build the row hash (the size, the offset)? 
Thanks in advance!
![usa](https://cloud.githubusercontent.com/assets/8455407/6745528/b11a65de-ceea-11e4-8f23-96447a28e1a7.gif)

**Comment by dhthong92** [comment]
ah I've test your streaming.js with massive dataset and it return an error: Each LinearRing of a Polygon must have 4 or more Positions. Any problem with it ???

**Comment by derrickpelletier** [comment]
The algorithm only generates a set based on a single precision level.

The algorithm essentially slices a row off of the poly and streams back the hashes that constitute that row based on the options provided (intersection, inside, etc).

Row bounding is found by taking a slice off the polygon for the current row and using the extent coordinates of that resulting poly.

It does not function like that image, no.

`rowHash` if i understand your question is just the first hash of the current row, because all hashes in the same row share the same latitudes. Simply found by taking the last one and getting the southerly neighbour which in this case is just a method of the geohash module being used.

If you throw your polygon that you tested with up on http://geojson.io i'll take a look for you.

**Comment by derrickpelletier** [comment]
I did end up doing something similar to that image once, using the results of this library.
I think i just streamed the resulting hashes into a leveldb using the hash as the key, and then iterated through to reduce the hashes when there were 32 hashes sharing a common parent hash, they're all sorted this way so it's easy. A little brute force, but at least it doesn't require rewriting the algorithm.

**Comment by dhthong92** [comment]
I think I've got your idea. So the basic concept is that you divide the polygon to several rows, and with each row you build its hash. But I think it works well with single polygon, so what's happen if we have more than 1 million polygon whose latitude is same with each other about 75%. You have to recalculate the row lots of times. Do I know right? 
I think that with your idea, we can pre-process by dividing all polygon to several bins one time only and save it in any buffer, stack or queue. Any idea?
About the polygon that I tested, I took it from your source code : /examples/streaming.js (var massive)

**Comment by derrickpelletier** [comment]
It doesn't divide the polygon into several rows first, it only slices a row off the main polygon on each iteration and then generates the hashes for that row.

Not sure in what case you'd be dealing with a million polygons sharing the same latitude 75% of the time? This certainly doesn't sound like a common use case worth optimizing for in a module meant to be more general.

This was designed to be more efficient in that you can stream in polygons from a file and stream out hashes, as opposed to preprocessing an arbitrary amount (millions) of polygons and then having to keep them in memory.

**Comment by derrickpelletier** [comment]
Thanks for the bug on the massive poly, will take a look.

**Comment by dhthong92** [comment]
Okay, thanks for your explaination, now I understand. But as I ask you in the first post, could I return different geohash level in one run?

**Comment by derrickpelletier** [comment]
Unfortunately no, not with how this is implemented. 

But you can just store your results of the run, sort them. Then iterate through and compare their parent hash. So if you ran it at precision 7, compare their 6th precision. If 32 of them match you can delete all 32 and replace them with a single precision 6.
